default:
  # requiring the environment of NodeJS 10
  image: node:12
  tags:
    - dind
pages:
  stage: deploy
  only:
    - stage
  script:
    - npm i
    - npm run prod
    - mv dist public
  artifacts:
    paths:
      - public
    expire_in: 1 week
deploy-main:
  stage: deploy
  when: manual
  only:
    - main
  script:
    - npm i
    - npm run prod
    - mkdir ./php-latest
    - git clone $REMOTE_REPO_URL ./php-latest
    - cd ./php-latest
    - git config user.email "$GITLAB_USER_EMAIL"
    - git config user.name "$GITLAB_USER_NAME"
    - git checkout html-latest
    - git merge origin/stage
    - rm -rf ./html
    - mv ../dist ./html
    - git add ./html
    - git commit -m "build html $CI_COMMIT_TIMESTAMP"
    - git push -f origin html-latest